name: "Issue Labeler"
description: "trigger an action based on issue comment"
inputs:
  github-token:
    description: "Github token"
    required: true
  keywords:
    description: "keywords to look for in the issue"
    required: true
  assignees:
    description: "assignees to be assigned when keyword is found"
  labels:
    description: "labels to be set when keyword is found"

outputs:
  title:
    description: "Title of Issue"
  body:
    description: "Body of Issue"
runs:
  using: "node12"
  main: "lib/index.js"
branding:
  icon: alert-circle
  color: gray-dark
