name: "Issue Labeler"
description: "trigger an action based on issue comment"
inputs:
  github-token:
    description: "Github token"
    required: true
  keywords:
    description: "keywords to look for in the issue"
    required: true
  assignees:
    description: "assignees to be assigned when keyword is found"
  labels:
    description: "labels to be set when keyword is found"
  title-or-body:
    description: "Whether to check the issue title, the issue body, or both for matching keywords"
    required: false
    default: "both"

outputs:
  title:
    description: "Title of Issue"
  body:
    description: "Body of Issue"
  labeled:
    description: "\"true\" if labeled otherwise \"false\""
  assigned:
    description: "\"true\" if assigned otherwise \"false\""
runs:
  using: "node12"
  main: "lib/index.js"
branding:
  icon: alert-circle
  color: gray-dark
